### ISSUE TITLE
No filesystem header on OSX

### ISSUE THREAD

**Issue by emrsmsrli** [lefticus/cpp_box#39]
Apple LLVM version 10.0.1 does not come with filesystem library header, resulting in an error on compilation. experimental/filesystem is also cannot be found.

Any workarounds?

**Comment by Ybalrid** [comment]
I had issues building C++17 code on macOs in the past. I resulted into installing a up-to-date version of LLVM with the homebrew package manager

https://brew.sh/

Once you've setup homebrew, this should do the trick:
```bash
$ brew install llvm
```

You probably need to setup the CC and CXX envrionement variable to point to the newly installed toolchain, you can do that directly in the CMake call

```bash
$ CC=/path/to/clang CXX=/path/to/clang++ cmake <path_to_source_code_with_cmakelists.txt>
```

I haven't done that in some time, and I haven't tested that on this project, but installing an up-to-date version of  LLVM or GCC on your system is likely to be the only solution.
